# Generated by Django 2.2.4 on 2019-09-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchera', '0002_research_re_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('specifications', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('pro_id', models.IntegerField()),
            ],
        ),
    ]
