# Generated by Django 2.2.4 on 2019-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchera', '0003_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='link',
            field=models.URLField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='re_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
