# Generated by Django 2.2.4 on 2019-09-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchera', '0004_auto_20190908_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='link',
            field=models.FileField(upload_to='media/'),
        ),
    ]
